version: "3.8"

services:
  api:
    build: ./backend
    image: my-fastapi-app:latest
    container_name: fastapi_container
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env  # Path to the .env file in the 'backend' directory
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:



