version: "3.8"

services:
  api:
    build: ./backend
    image: my-fastapi-app:latest
    container_name: fastapi_container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=root
      - DB_PASSWORD=6521
    # If you have volumes to persist data, they'd go here
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=6521
      - MYSQL_DATABASE=mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
